### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [AlvaroMartinFernandez/InstagramPost#2]
Bien hecho!

Únicos comentarios:
Falta una etiqueta de cierre en la imagen de la línea 31 Deberías evitar mezclar inglés-español en nombres de clases (ej. headPost-izquierda)
* Deberías evitar mezclar convenciones al nombrar clases (PascalCase vs. kebab-case vs. camelCase. Ej. headPost - headPost-izquierda - Title)

Comprometernos con una convención hace que mis nombres sean previsibles y tenga que consultar menos el código y sea menos propenso a cometer errores tipográficos. Para CSS te recomendaría kebab-case

**Comment by AlvaroMartinFernandez** [comment]
Buenas ya realice los cambios indicados
